import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { sendLeaveDecisionEmail, sendLeaveSubmittedEmail, sendPayrollUpdateEmail } from '../lib/mailer.js';

const router = Router();
router.use(requireAuth);
const admin = requireRole('ADMIN', 'HR');
const dateSchema = z.string().datetime({ offset: true }).or(z.string().date());
const page = (query: Record<string, unknown>) => ({ page: Math.max(1, Number(query.page) || 1), limit: Math.min(100, Math.max(1, Number(query.limit) || 20)) });
const day = () => { const value = new Date(); value.setUTCHours(0, 0, 0, 0); return value; };
const safeProfile = { id: true, userId: true, firstName: true, lastName: true, phone: true, address: true, dateOfBirth: true, emergencyName: true, emergencyPhone: true, profilePictureUrl: true, designation: true, department: true, joiningDate: true, employmentStatus: true, user: { select: { employeeId: true, email: true, role: true, isActive: true, emailVerified: true } } } as const;

router.get('/employees/me', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id }, select: safeProfile }); response.json({ success: true, data: profile }); } catch (error) { next(error); } });
router.patch('/employees/me', async (request, response, next) => { try { const input = z.object({ firstName: z.string().trim().min(1).max(80).optional(), lastName: z.string().trim().min(1).max(80).optional(), phone: z.string().max(30).optional(), address: z.string().max(500).optional(), dateOfBirth: dateSchema.optional(), emergencyName: z.string().max(100).optional(), emergencyPhone: z.string().max(30).optional() }).parse(request.body); const profile = await prisma.employeeProfile.update({ where: { userId: request.user!.id }, data: { ...input, dateOfBirth: input.dateOfBirth ? new Date(input.dateOfBirth) : undefined }, select: safeProfile }); response.json({ success: true, data: profile }); } catch (error) { next(error); } });
router.get('/employees', admin, async (request, response, next) => { try { const { page: current, limit } = page(request.query); const search = typeof request.query.search === 'string' ? request.query.search : undefined; const where = { OR: search ? [{ firstName: { contains: search, mode: 'insensitive' as const } }, { lastName: { contains: search, mode: 'insensitive' as const } }, { user: { employeeId: { contains: search, mode: 'insensitive' as const } } }] : undefined, department: typeof request.query.department === 'string' ? request.query.department : undefined }; const [data, total] = await Promise.all([prisma.employeeProfile.findMany({ where, select: safeProfile, skip: (current - 1) * limit, take: limit, orderBy: { lastName: 'asc' } }), prisma.employeeProfile.count({ where })]); response.json({ success: true, data, meta: { page: current, limit, total, totalPages: Math.ceil(total / limit) } }); } catch (error) { next(error); } });
router.get('/employees/:id', admin, async (request, response, next) => { try { const id = z.string().min(1).parse(request.params.id); const data = await prisma.employeeProfile.findUniqueOrThrow({ where: { id }, select: safeProfile }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.patch('/employees/:id', admin, async (request, response, next) => { try { const id = z.string().min(1).parse(request.params.id); const input = z.object({ firstName: z.string().min(1).optional(), lastName: z.string().min(1).optional(), phone: z.string().optional(), address: z.string().optional(), designation: z.string().optional(), department: z.string().optional(), employmentStatus: z.enum(['ACTIVE', 'INACTIVE', 'ON_LEAVE']).optional(), joiningDate: dateSchema.optional() }).parse(request.body); const data = await prisma.employeeProfile.update({ where: { id }, data: { ...input, joiningDate: input.joiningDate ? new Date(input.joiningDate) : undefined }, select: safeProfile }); response.json({ success: true, data }); } catch (error) { next(error); } });

router.post('/attendance/check-in', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const existing = await prisma.attendance.findUnique({ where: { employeeId_date: { employeeId: profile.id, date: day() } } }); if (existing?.checkIn) { response.status(409).json({ success: false, message: 'You have already checked in today', error: { code: 'ATTENDANCE_ALREADY_CHECKED_IN' } }); return; } const data = existing ? await prisma.attendance.update({ where: { id: existing.id }, data: { checkIn: new Date(), status: 'PRESENT' } }) : await prisma.attendance.create({ data: { employeeId: profile.id, date: day(), checkIn: new Date(), status: 'PRESENT' } }); response.status(201).json({ success: true, message: 'Attendance checked in successfully', data }); } catch (error) { next(error); } });
router.post('/attendance/check-out', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const existing = await prisma.attendance.findUnique({ where: { employeeId_date: { employeeId: profile.id, date: day() } } }); if (!existing?.checkIn) { response.status(400).json({ success: false, message: 'Check-in is required before check-out', error: { code: 'ATTENDANCE_CHECK_IN_REQUIRED' } }); return; } if (existing.checkOut) { response.status(409).json({ success: false, message: 'You have already checked out today', error: { code: 'ATTENDANCE_ALREADY_CHECKED_OUT' } }); return; } const checkOut = new Date(); const data = await prisma.attendance.update({ where: { id: existing.id }, data: { checkOut, status: checkOut.getTime() - existing.checkIn.getTime() < 4 * 3600000 ? 'HALF_DAY' : 'PRESENT' } }); response.json({ success: true, message: 'Attendance checked out successfully', data }); } catch (error) { next(error); } });
async function attendanceFor(request: Parameters<typeof router.get>[1] extends never ? never : any, response: any, next: any) { try { const profileId = request.user!.role === 'EMPLOYEE' ? (await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } })).id : request.params.employeeId; const { page: current, limit } = page(request.query); const from = typeof request.query.startDate === 'string' ? new Date(request.query.startDate) : undefined; const to = typeof request.query.endDate === 'string' ? new Date(request.query.endDate) : undefined; const where = { employeeId: profileId, ...(from || to ? { date: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {}) }; const [data, total] = await Promise.all([prisma.attendance.findMany({ where, orderBy: { date: 'desc' }, skip: (current - 1) * limit, take: limit }), prisma.attendance.count({ where })]); response.json({ success: true, data, meta: { page: current, limit, total, totalPages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
router.get('/attendance', admin, async (request, response, next) => { try { const { page: current, limit } = page(request.query); const where = { ...(typeof request.query.employeeId === 'string' ? { employeeId: request.query.employeeId } : {}), ...(typeof request.query.status === 'string' ? { status: z.enum(['PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE']).parse(request.query.status) } : {}), ...(typeof request.query.startDate === 'string' || typeof request.query.endDate === 'string' ? { date: { ...(typeof request.query.startDate === 'string' ? { gte: new Date(request.query.startDate) } : {}), ...(typeof request.query.endDate === 'string' ? { lte: new Date(request.query.endDate) } : {}) } } : {}) }; const [data, total] = await Promise.all([prisma.attendance.findMany({ where, include: { employee: { select: { firstName: true, lastName: true, department: true, user: { select: { employeeId: true } } } } }, orderBy: { date: 'desc' }, skip: (current - 1) * limit, take: limit }), prisma.attendance.count({ where })]); response.json({ success: true, data, meta: { page: current, limit, total, totalPages: Math.ceil(total / limit) } }); } catch (error) { next(error); } });
router.get('/attendance/me', attendanceFor); router.get('/attendance/:employeeId', admin, attendanceFor);
router.get('/attendance/me/daily', attendanceFor); router.get('/attendance/me/weekly', attendanceFor);
router.get('/attendance/:employeeId/daily', admin, attendanceFor); router.get('/attendance/:employeeId/weekly', admin, attendanceFor);

router.post('/leaves', async (request, response, next) => { try { const input = z.object({ type: z.enum(['PAID', 'SICK', 'UNPAID']), startDate: dateSchema, endDate: dateSchema, remarks: z.string().max(1000).optional() }).refine((value) => new Date(value.startDate) <= new Date(value.endDate), 'startDate cannot be after endDate').parse(request.body); const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const overlap = await prisma.leaveRequest.findFirst({ where: { employeeId: profile.id, status: { in: ['PENDING', 'APPROVED'] }, startDate: { lte: new Date(input.endDate) }, endDate: { gte: new Date(input.startDate) } } }); if (overlap) { response.status(409).json({ success: false, message: 'Leave dates overlap an existing request', error: { code: 'LEAVE_OVERLAP' } }); return; } const data = await prisma.leaveRequest.create({ data: { employeeId: profile.id, type: input.type, startDate: new Date(input.startDate), endDate: new Date(input.endDate), remarks: input.remarks } }); void sendLeaveSubmittedEmail((await prisma.user.findUniqueOrThrow({ where: { id: request.user!.id } })).email, data.startDate, data.endDate); response.status(201).json({ success: true, data }); } catch (error) { next(error); } });
router.get('/leaves/me', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const data = await prisma.leaveRequest.findMany({ where: { employeeId: profile.id }, orderBy: { createdAt: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/leaves/:id', async (request, response, next) => { try { const leave = await prisma.leaveRequest.findUniqueOrThrow({ where: { id: z.string().parse(request.params.id) }, include: { employee: true } }); if (request.user!.role === 'EMPLOYEE' && leave.employee.userId !== request.user!.id) { response.status(403).json({ success: false, message: 'Insufficient permissions', error: { code: 'FORBIDDEN' } }); return; } response.json({ success: true, data: leave }); } catch (error) { next(error); } });
router.patch('/leaves/:id/cancel', async (request, response, next) => { try { const id = z.string().parse(request.params.id); const leave = await prisma.leaveRequest.findUniqueOrThrow({ where: { id }, include: { employee: true } }); if (leave.employee.userId !== request.user!.id || leave.status !== 'PENDING') { response.status(409).json({ success: false, message: 'Only your pending requests can be cancelled', error: { code: 'LEAVE_CANNOT_CANCEL' } }); return; } const data = await prisma.leaveRequest.update({ where: { id }, data: { status: 'CANCELLED' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/leaves', admin, async (_request, response, next) => { try { const data = await prisma.leaveRequest.findMany({ include: { employee: { select: safeProfile } }, orderBy: { createdAt: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.post('/leaves/:id/approve', admin, async (request, response, next) => { await reviewLeave(request, response, next, 'APPROVED'); });
router.post('/leaves/:id/reject', admin, async (request, response, next) => { await reviewLeave(request, response, next, 'REJECTED'); });
async function reviewLeave(request: any, response: any, next: any, status: 'APPROVED' | 'REJECTED') { try { const comment = z.object({ comment: z.string().max(1000).optional() }).parse(request.body ?? {}).comment; const leave = await prisma.leaveRequest.findUniqueOrThrow({ where: { id: request.params.id }, include: { employee: { include: { user: true } } } }); if (leave.status !== 'PENDING') { response.status(409).json({ success: false, message: 'Only pending leave requests can be reviewed', error: { code: 'LEAVE_NOT_PENDING' } }); return; } const data = await prisma.$transaction(async (tx) => { const updated = await tx.leaveRequest.update({ where: { id: leave.id }, data: { status, reviewerId: request.user!.id, reviewerComment: comment, reviewedAt: new Date() } }); if (status === 'APPROVED') { const cursor = new Date(leave.startDate); while (cursor <= leave.endDate) { await tx.attendance.upsert({ where: { employeeId_date: { employeeId: leave.employeeId, date: new Date(cursor) } }, create: { employeeId: leave.employeeId, date: new Date(cursor), status: 'LEAVE', remarks: `Approved ${leave.type} leave` }, update: { status: 'LEAVE', remarks: `Approved ${leave.type} leave` } }); cursor.setUTCDate(cursor.getUTCDate() + 1); } } await tx.notification.create({ data: { recipientId: leave.employee.userId, type: status === 'APPROVED' ? 'LEAVE_APPROVED' : 'LEAVE_REJECTED', title: `Leave ${status.toLowerCase()}`, message: comment ?? `Your leave request was ${status.toLowerCase()}.` } }); return updated; }); void sendLeaveDecisionEmail(leave.employee.user.email, status === 'APPROVED', comment); response.json({ success: true, data }); } catch (error) { next(error); } }

router.get('/payroll/me', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const data = await prisma.salaryStructure.findFirst({ where: { employeeId: profile.id }, orderBy: { effectiveDate: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/payroll/me/history', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const data = await prisma.salaryStructure.findMany({ where: { employeeId: profile.id }, orderBy: { effectiveDate: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/payroll/me/:period', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const data = await prisma.salaryStructure.findFirst({ where: { employeeId: profile.id, effectiveDate: { lte: new Date(`${request.params.period}-01`) } }, orderBy: { effectiveDate: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/payroll/:employeeId', admin, async (request, response, next) => { try { const employeeId = z.string().min(1).parse(request.params.employeeId); const data = await prisma.salaryStructure.findFirst({ where: { employeeId }, orderBy: { effectiveDate: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/payroll/:employeeId/history', admin, async (request, response, next) => { try { const employeeId = z.string().min(1).parse(request.params.employeeId); const data = await prisma.salaryStructure.findMany({ where: { employeeId }, orderBy: { effectiveDate: 'desc' } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.put('/payroll/:employeeId', admin, async (request, response, next) => { try { const employeeId = z.string().min(1).parse(request.params.employeeId); const input = z.object({ basicSalary: z.coerce.number().nonnegative(), allowances: z.coerce.number().nonnegative().default(0), deductions: z.coerce.number().nonnegative().default(0), effectiveDate: dateSchema }).parse(request.body); const grossSalary = input.basicSalary + input.allowances; const data = await prisma.salaryStructure.create({ data: { employeeId, basicSalary: input.basicSalary, allowances: input.allowances, deductions: input.deductions, grossSalary, netSalary: grossSalary - input.deductions, effectiveDate: new Date(input.effectiveDate) } }); const employee = await prisma.employeeProfile.findUnique({ where: { id: employeeId }, include: { user: true } }); if (employee) void sendPayrollUpdateEmail(employee.user.email); response.status(201).json({ success: true, data }); } catch (error) { next(error); } });

router.get('/notifications', async (request, response, next) => { try { const data = await prisma.notification.findMany({ where: { recipientId: request.user!.id }, orderBy: { createdAt: 'desc' }, take: 100 }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/notifications/unread-count', async (request, response, next) => { try { const count = await prisma.notification.count({ where: { recipientId: request.user!.id, read: false } }); response.json({ success: true, data: { count } }); } catch (error) { next(error); } });
router.patch('/notifications/:id/read', async (request, response, next) => { try { const data = await prisma.notification.updateMany({ where: { id: request.params.id, recipientId: request.user!.id }, data: { read: true } }); response.json({ success: true, data: { updated: data.count } }); } catch (error) { next(error); } });
router.patch('/notifications/read-all', async (request, response, next) => { try { await prisma.notification.updateMany({ where: { recipientId: request.user!.id, read: false }, data: { read: true } }); response.json({ success: true, message: 'Notifications marked as read' }); } catch (error) { next(error); } });

router.get('/dashboard/employee', async (request, response, next) => { try { const profile = await prisma.employeeProfile.findUniqueOrThrow({ where: { userId: request.user!.id } }); const [attendance, leaves, salary, unread] = await Promise.all([prisma.attendance.findUnique({ where: { employeeId_date: { employeeId: profile.id, date: day() } } }), prisma.leaveRequest.findMany({ where: { employeeId: profile.id }, orderBy: { createdAt: 'desc' }, take: 5 }), prisma.salaryStructure.findFirst({ where: { employeeId: profile.id }, orderBy: { effectiveDate: 'desc' } }), prisma.notification.count({ where: { recipientId: request.user!.id, read: false } })]); response.json({ success: true, data: { profile, todayAttendance: attendance, recentLeaves: leaves, salarySummary: salary, unreadNotifications: unread } }); } catch (error) { next(error); } });
router.get('/dashboard/admin', admin, async (_request, response, next) => { try { const [employees, activeEmployees, pendingLeaves, today] = await Promise.all([prisma.employeeProfile.count(), prisma.employeeProfile.count({ where: { employmentStatus: 'ACTIVE' } }), prisma.leaveRequest.count({ where: { status: 'PENDING' } }), prisma.attendance.groupBy({ by: ['status'], where: { date: day() }, _count: true })]); response.json({ success: true, data: { employeeCount: employees, activeEmployees, pendingLeaveRequests: pendingLeaves, todayAttendance: today } }); } catch (error) { next(error); } });
router.get('/reports/attendance', admin, async (request, response, next) => { try { const where = { ...(typeof request.query.employeeId === 'string' ? { employeeId: request.query.employeeId } : {}), ...(typeof request.query.department === 'string' ? { employee: { department: request.query.department } } : {}), ...(typeof request.query.status === 'string' ? { status: z.enum(['PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE']).parse(request.query.status) } : {}), ...(typeof request.query.startDate === 'string' || typeof request.query.endDate === 'string' ? { date: { ...(typeof request.query.startDate === 'string' ? { gte: new Date(request.query.startDate) } : {}), ...(typeof request.query.endDate === 'string' ? { lte: new Date(request.query.endDate) } : {}) } } : {}) }; const data = await prisma.attendance.groupBy({ by: ['status'], where, _count: { _all: true } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/reports/attendance/summary', admin, async (request, response, next) => { try { const status = await prisma.attendance.groupBy({ by: ['status'], _count: { _all: true } }); response.json({ success: true, data: { byStatus: status, filters: request.query } }); } catch (error) { next(error); } });
router.get('/reports/leaves', admin, async (request, response, next) => { try { const where = { ...(typeof request.query.employeeId === 'string' ? { employeeId: request.query.employeeId } : {}), ...(typeof request.query.type === 'string' ? { type: z.enum(['PAID', 'SICK', 'UNPAID']).parse(request.query.type) } : {}), ...(typeof request.query.status === 'string' ? { status: z.enum(['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED']).parse(request.query.status) } : {}), ...(typeof request.query.startDate === 'string' || typeof request.query.endDate === 'string' ? { startDate: { ...(typeof request.query.startDate === 'string' ? { gte: new Date(request.query.startDate) } : {}), ...(typeof request.query.endDate === 'string' ? { lte: new Date(request.query.endDate) } : {}) } } : {}) }; const data = await prisma.leaveRequest.groupBy({ by: ['type', 'status'], where, _count: { _all: true } }); response.json({ success: true, data }); } catch (error) { next(error); } });
router.get('/reports/payroll', admin, async (request, response, next) => { try { const where = { ...(typeof request.query.employeeId === 'string' ? { employeeId: request.query.employeeId } : {}), ...(typeof request.query.department === 'string' ? { employee: { department: request.query.department } } : {}), ...(typeof request.query.startDate === 'string' || typeof request.query.endDate === 'string' ? { effectiveDate: { ...(typeof request.query.startDate === 'string' ? { gte: new Date(request.query.startDate) } : {}), ...(typeof request.query.endDate === 'string' ? { lte: new Date(request.query.endDate) } : {}) } } : {}) }; const { page: current, limit } = page(request.query); const [data, total] = await Promise.all([prisma.salaryStructure.findMany({ where, orderBy: { effectiveDate: 'desc' }, skip: (current - 1) * limit, take: limit, include: { employee: { select: { firstName: true, lastName: true, department: true, user: { select: { employeeId: true } } } } } }), prisma.salaryStructure.count({ where })]); response.json({ success: true, data, meta: { page: current, limit, total, totalPages: Math.ceil(total / limit) } }); } catch (error) { next(error); } });
router.get('/reports/employees', admin, async (request, response, next) => { try { const where = { ...(typeof request.query.department === 'string' ? { department: request.query.department } : {}), ...(typeof request.query.status === 'string' ? { employmentStatus: z.enum(['ACTIVE', 'INACTIVE', 'ON_LEAVE']).parse(request.query.status) } : {}), ...(typeof request.query.search === 'string' ? { OR: [{ firstName: { contains: request.query.search, mode: 'insensitive' as const } }, { lastName: { contains: request.query.search, mode: 'insensitive' as const } }] } : {}) }; const data = await prisma.employeeProfile.groupBy({ by: ['department', 'employmentStatus'], where, _count: { _all: true } }); response.json({ success: true, data }); } catch (error) { next(error); } });

export default router;
