import { useState } from 'react'
import { PageHeader, SearchInput } from '../components/AdminPageParts'
import { statusClass } from '../utils/status'

export function EmployeeModal({ employee, onClose, onEdit, onSave, detailOnly = false }) {
  const [draft, setDraft] = useState(employee || { name: '', role: '', department: 'Engineering', email: '', phone: '', joined: 'Aug 22, 2026', status: 'Active', initials: 'NE', tone: 'blue' })
  const update = (field, value) => setDraft({ ...draft, [field]: value })
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="employee-modal-title"><div className="modal-heading"><div><p className="eyebrow">{detailOnly ? 'Employee profile' : employee ? 'Edit employee' : 'New employee'}</p><h2 id="employee-modal-title">{detailOnly ? draft.name : employee ? 'Update details' : 'Add employee'}</h2></div><button type="button" className="close-button" onClick={onClose} aria-label="Close">x</button></div>{detailOnly ? <div className="detail-content"><span className={`detail-avatar ${draft.tone}`}>{draft.initials}</span><div className="detail-grid"><span>Role<strong>{draft.role}</strong></span><span>Department<strong>{draft.department}</strong></span><span>Email<strong>{draft.email}</strong></span><span>Phone<strong>{draft.phone}</strong></span><span>Joined<strong>{draft.joined}</strong></span><span>Status<strong><span className={`status-pill ${statusClass(draft.status)}`}>{draft.status}</span></strong></span></div><button type="button" className="primary-button" onClick={() => onEdit(draft)}>Edit profile</button></div> : <form className="employee-form" onSubmit={(event) => { event.preventDefault(); onSave({ ...draft, name: draft.name || 'New employee', initials: draft.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'NE' }) }}><label>Full name<input required value={draft.name} onChange={(event) => update('name', event.target.value)} /></label><label>Role<input required value={draft.role} onChange={(event) => update('role', event.target.value)} /></label><label>Department<select value={draft.department} onChange={(event) => update('department', event.target.value)}><option>Engineering</option><option>Design</option><option>Finance</option><option>Marketing</option><option>People</option><option>Sales</option></select></label><label>Email<input type="email" required value={draft.email} onChange={(event) => update('email', event.target.value)} /></label><label>Phone<input value={draft.phone} onChange={(event) => update('phone', event.target.value)} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">Save employee</button></div></form>}</section></div>
}

export function PeoplePage({ employees, onAdd, onEdit, onView }) {
  const [query, setQuery] = useState('')
  const [department, setDepartment] = useState('All departments')
  const [page, setPage] = useState(1)
  const pageSize = 5
  const filtered = employees.filter((employee) => `${employee.name} ${employee.role} ${employee.email}`.toLowerCase().includes(query.toLowerCase()) && (department === 'All departments' || employee.department === department))
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize))
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize)
  const updateQuery = (value) => { setQuery(value); setPage(1) }
  return <><PageHeader eyebrow="People directory" title="Employees" copy="Manage your people, roles, and team details." action={<button type="button" className="primary-button" onClick={onAdd}><span>+</span> Add employee</button>} /><section className="panel table-panel"><div className="table-toolbar"><SearchInput value={query} onChange={updateQuery} placeholder="Search employees" /><select value={department} onChange={(event) => { setDepartment(event.target.value); setPage(1) }} aria-label="Filter by department"><option>All departments</option><option>Design</option><option>Engineering</option><option>Finance</option><option>Marketing</option><option>People</option><option>Sales</option></select><span className="result-count">{filtered.length} employees</span></div><div className="table-scroll"><table><thead><tr><th>Employee</th><th>Role</th><th>Department</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><button type="button" className="person-cell" onClick={() => onView(item)}><span className={`table-avatar ${item.tone}`}>{item.initials}</span><span><strong>{item.name}</strong><small>{item.email}</small></span></button></td><td>{item.role}</td><td>{item.department}</td><td><span className={`status-pill ${statusClass(item.status)}`}>{item.status}</span></td><td><button type="button" className="row-action" onClick={() => onEdit(item)}>Edit</button></td></tr>)}</tbody></table></div>{!visible.length && <div className="empty-state"><strong>No employees found</strong><span>Try a different name or department.</span></div>}<div className="pagination"><span>Showing {visible.length ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, filtered.length)} of {filtered.length}</span><div><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><b>{page} / {pageCount}</b><button type="button" disabled={page === pageCount} onClick={() => setPage(page + 1)}>Next</button></div></div></section></>
}